### ISSUE TITLE
Update to IG broke the script, must update selector probably

### ISSUE THREAD

**Issue by kitalia** [Oxlac/MR.DM#11]
**Describe the bug**
### Update to IG broke the script, must update selector probably

**To Reproduce**

Try to send a DM and:

```
[DEBUG  ] Finished Request
 Exception in thread Thread-4 (_start_messages):
 Traceback (most recent call last):
   File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
     self.run()
   File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
     self._target(*self._args, **self._kwargs)
   File "/Users/x/Desktop/git/mr.dm/src/ui/progressscreen/progressscreen.py", line 232, in _start_messages
     if self.find_element(SELECTORS["save_login_info"]):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/Users/x/Desktop/git/mr.dm/src/ui/progressscreen/progressscreen.py", line 311, in find_element
     return self.session.driver.find_element(By.XPATH, XPATH)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 742, in find_element
     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
     self.error_handler.check_response(response)
   File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
     raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()='Save info']"}
   (Session info: chrome=121.0.6167.85); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
```

**Expected behavior**
a DM should be sent

**Desktop (please complete the following information):**
any

**Comment by Guhan-SenSam** [comment]
Will take a look at this and update
