### ISSUE TITLE
Bot gets stuck after it inputs the Username

### ISSUE THREAD

**Issue by cyberwombat1337** [Oxlac/MR.DM#12]
**Describe the bug**
I am not sure if it's something that has to do with the selectors. The Bot is supposed to proceed with the DM, but gets stuck after entering name of User.

**To Reproduce**

1. After it inputs the Username, it gets stuck with the procedure.

**Expected behavior**
After input its supposed to send the DM.

**Screenshots**

This is the Log im getting:
![screenshot](https://github.com/Oxlac/MR.DM/assets/160140608/3618ce68-32d9-425a-b442-80798aa4dfa8)

```
[DEBUG  ] Finished Request
 Exception in thread Thread-5 (_start_messages):
 Traceback (most recent call last):
   File "C:\Program Files\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
     self.run()
   File "C:\Program Files\Python312\Lib\threading.py", line 989, in run
     self._target(*self._args, **self._kwargs)
   File "C:\Users\Wombaterino\Desktop\MR.IG\MR.DM\src\ui\progressscreen\progressscreen.py", line 245, in _start_messages
     self.start_message_loop()
   File "C:\Users\Wombaterino\Desktop\MR.IG\MR.DM\src\ui\progressscreen\progressscreen.py", line 266, in start_message_loop
     self.find_element(SELECTORS["dm_select_user"].format(user[1])).click()
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
     self._execute(Command.CLICK_ELEMENT)
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
     return self._parent.execute(command, params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
     self.error_handler.check_response(response)
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
     raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span class="x1lliihq x193iq5w x6ikm8r x10wlt62 xlyipyv xuxw1ft">...</span> is not clickable at point (193, 286). Other element would receive the click: <div class="x1qjc9v5 x9f619 x78zum5 xdt5ytf x1iyjqo2 xl56j7k" style="--card-background: rgb(var(--ig-primary-background)); --comment-background: rgb(var(--ig-highlight-background)); --filter-primary-icon: invert(100%); --messenger-card-background: rgb(var(--ig-primary-background)); --mwp-message-list-actions-width: 96px; --mwp-message-row-background: rgb(var(--ig-primary-background)); --primary-text: rgb(var(--ig-primary-text));">...</div>
   (Session info: chrome=121.0.6167.184)
 Stacktrace:
        GetHandleVerifier [0x00007FF789277012+3522402]
        (No symbol) [0x00007FF788E98352]
        (No symbol) [0x00007FF788D45ABB]
        (No symbol) [0x00007FF788D93390]
        (No symbol) [0x00007FF788D910D2]
        (No symbol) [0x00007FF788D8E834]
        (No symbol) [0x00007FF788D8D569]
        (No symbol) [0x00007FF788D81910]
        (No symbol) [0x00007FF788DAF05A]
        (No symbol) [0x00007FF788D8120A]
        (No symbol) [0x00007FF788DAF270]
        (No symbol) [0x00007FF788DCBDA3]
        (No symbol) [0x00007FF788DAEE03]
        (No symbol) [0x00007FF788D7F4D4]
        (No symbol) [0x00007FF788D805F1]
        GetHandleVerifier [0x00007FF7892A9B9D+3730157]
        GetHandleVerifier [0x00007FF7892FF02D+4079485]
        GetHandleVerifier [0x00007FF7892F75D3+4048163]
        GetHandleVerifier [0x00007FF788FCA649+718233]
        (No symbol) [0x00007FF788EA4A3F]
        (No symbol) [0x00007FF788E9FA94]
        (No symbol) [0x00007FF788E9FBC2]
        (No symbol) [0x00007FF788E8F2E4]
        BaseThreadInitThunk [0x00007FF82B8E7344+20]
        RtlUserThreadStart [0x00007FF82D8426B1+33]
```

**AFTER I CLOSE THE SCRIPT LOG:**

```
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\Wombaterino\Desktop\MR.IG\MR.DM\src\main.py", line 67, in <module>
     MyApp().run()
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\kivy\app.py", line 956, in run
     runTouchApp()
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
                        ^^^^^^^^^^^
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\kivy\clock.py", line 689, in idle
     usleep(1000000 * sleeptime)
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\kivy\clock.py", line 965, in usleep
     _usleep(microseconds, self._sleep_obj)
   File "C:\Users\Wombaterino\AppData\Roaming\Python\Python312\site-packages\kivy\clock.py", line 504, in _usleep
     _kernel32.WaitForSingleObject(obj, 0xffffffff)
 KeyboardInterrupt

```
**Desktop (please complete the following information):**
Any

**Comment by cyberwombat1337** [comment]
so the dev do not give a fuck I guess? well played.
