### ISSUE TITLE
CSV NotImplementedError()

### ISSUE THREAD

**Issue by Nirmal2000** [Oxlac/MR.DM#17]
Firstly thanks for this amazing open source product! I just have an issue uploading CSV
I get the below error

```
Traceback (most recent call last):
   File "/Users/nirmal/Desktop/MR.DM/src/main.py", line 67, in <module>
     MyApp().run()
   File "/Users/nirmal/miniconda3/envs/mrdm/lib/python3.11/site-packages/kivy/app.py", line 956, in run
     runTouchApp()
   File "/Users/nirmal/miniconda3/envs/mrdm/lib/python3.11/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/Users/nirmal/miniconda3/envs/mrdm/lib/python3.11/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/Users/nirmal/miniconda3/envs/mrdm/lib/python3.11/site-packages/kivy/base.py", line 383, in idle
     self.dispatch_input()
   File "/Users/nirmal/miniconda3/envs/mrdm/lib/python3.11/site-packages/kivy/base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/Users/nirmal/miniconda3/envs/mrdm/lib/python3.11/site-packages/kivy/base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/Users/nirmal/miniconda3/envs/mrdm/lib/python3.11/site-packages/kivymd/uix/behaviors/ripple_behavior.py", line 404, in on_touch_up
     return super().on_touch_up(touch)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/Users/nirmal/miniconda3/envs/mrdm/lib/python3.11/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/Users/nirmal/Desktop/MR.DM/src/ui/accountselectscreen/accountselectscreen.py", line 180, in import_csv
     filechooser.open_file(on_selection=self._import_csv_file)
   File "/Users/nirmal/miniconda3/envs/mrdm/lib/python3.11/site-packages/plyer/facades/filechooser.py", line 54, in open_file
     return self._file_selection_dialog(mode="open", *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/Users/nirmal/miniconda3/envs/mrdm/lib/python3.11/site-packages/plyer/facades/filechooser.py", line 74, in _file_selection_dialog
     raise NotImplementedError()
 NotImplementedError
```

**Comment by aryan-balodi** [comment]
has this been fixed since??
