### ISSUE TITLE
Not able to Message

### ISSUE THREAD

**Issue by pushkarsingh-03** [Oxlac/MR.DM#8]
Hey Can you please help me with this error, the bot is getting stuck again and again. I don't know what is the reason but I think the UI of my instagram is a bit different from what I saw in screenshots. Please help
<img width="1080" alt="Screenshot 2024-01-12 215554" src="https://github.com/Oxlac/MR.DM/assets/78078314/21316052-1ec0-4501-b4c2-979ec68997fe">

Exception in thread Thread-4 (_start_messages):
 Traceback (most recent call last):
   File "C:\Users\dashi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
     self.run()
   File "C:\Users\dashi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
     self._target(*self._args, **self._kwargs)
   File "C:\Users\dashi\OneDrive\Documents\GitHub\MR.DM\src\ui\progressscreen\progressscreen.py", line 241, in _start_messages
     self.start_message_loop()
   File "C:\Users\dashi\OneDrive\Documents\GitHub\MR.DM\src\ui\progressscreen\progressscreen.py", line 252, in start_message_loop
     self.find_element(SELECTORS["new_dm_btn"]).click()
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\dashi\OneDrive\Documents\GitHub\MR.DM\src\ui\progressscreen\progressscreen.py", line 307, in find_element
     return self.session.driver.find_element(By.XPATH, XPATH)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\dashi\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\dashi\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute     
     self.error_handler.check_response(response)
   File "C:\Users\dashi\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
     raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@role= 'button'][.//div//*//*[text()='New message']]"}
   (Session info: chrome=120.0.6099.217); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
 Stacktrace:
        GetHandleVerifier [0x00007FF7EEFF2142+3514994]
        (No symbol) [0x00007FF7EEC10CE2]
        (No symbol) [0x00007FF7EEAB76AA]
        (No symbol) [0x00007FF7EEB01860]
        (No symbol) [0x00007FF7EEB0197C]
        (No symbol) [0x00007FF7EEB44EE7]
        (No symbol) [0x00007FF7EEB2602F]
        (No symbol) [0x00007FF7EEB428F6]
        (No symbol) [0x00007FF7EEB25D93]
        (No symbol) [0x00007FF7EEAF4BDC]
        (No symbol) [0x00007FF7EEAF5C64]
        GetHandleVerifier [0x00007FF7EF01E16B+3695259]
        GetHandleVerifier [0x00007FF7EF076737+4057191]
        GetHandleVerifier [0x00007FF7EF06E4E3+4023827]
        GetHandleVerifier [0x00007FF7EED404F9+689705]
        (No symbol) [0x00007FF7EEC1C048]
        (No symbol) [0x00007FF7EEC18044]
        (No symbol) [0x00007FF7EEC181C9]
        (No symbol) [0x00007FF7EEC088C4]
        BaseThreadInitThunk [0x00007FFBC7D2257D+29]
        RtlUserThreadStart [0x00007FFBC9ACAA58+40]

**Comment by Guhan-SenSam** [comment]
Hello, It seems I had lost a line when I was resolving a merge conflict. The issue was in the code and not with a difference in Insta accounts. The latest commit has fixed this issue. Please clone the repo and try again
